### ISSUE TITLE
Template review feedback

### ISSUE THREAD

**Issue by praveena-pappu** [agilecrm/500apps-public-gtm-pushninja#5]
Thanks for submitting a template to the gallery, there were a few issues in your template that needed to be resolved ahead of approving the template for the gallery.

1) encodeUriComponent should be used on user provided values that are then used as parameters in your url. These methods take in a single text argument and return a URI Encoded string. You should use this method on "api_key" when generating the url
const trackingUrl='https://gtm.500apps.com/gtm/push/'+api_key+'.js';

**Comment by Shiva656** [comment]
Thanks for your response. I have updated the code as per your suggestions.

**Comment by Shiva656** [comment]
Any update ..?

**Comment by Shiva656** [comment]
@praveena-pappu any update on this..?

**Comment by Shiva656** [comment]
@praveena-pappu any update on this..?

**Comment by agilecrm** [comment]
This has been resolved long back and awaiting the inclusion in the template gallery
